# logging settings
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    mx.com.metalsa.soap.service.reports: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
      springframework:
        ws: DEBUG

# credentials for SOAP ws
userId: user
password: pass

# OracleDB connection settings
spring:
  datasource:
    url: jdbc:oracle:thin:@HOST:PORT:DB
    username: user
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

#spring:
#  datasource:
#    jndi-name: jdbc/t1core-spx
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect

